global:
  resolve_timeout: 5m
  #slack_api_url: '<incomming-webhook-url>'
  
route:
  receiver: 'slack'
  group_by: ['instance', 'job', 'severity']
  group_interval: 5m
  repeat_interval: 24h

receivers:
  - name: 'slack'
#    slack_configs:
#      - send_resolved: true
#        channel: '#notifications'
#        username: 'AlertManager'
#        api_url: '<incomming-webhook-url>'
#        title_link: 'http://alertmanager.localdns.xyz:9093/#/alerts'
#        title: '{{ if eq .Status "firing" }}:flushed:{{ else }}:sunglasses:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.summary }} (catchall)'
#        text: "{{ range .Alerts }}*Priority*: `{{ .Labels.severity | toUpper }}`\nTarget: {{ .Labels.instance }}\n{{ .Annotations.description }}\n{{ end }}"

#  - name: 'detailed-slack'
#    slack_configs:
#      - send_resolved: true
#        title_link: 'http://alertmanager.localdns.xyz:9093/#/alerts'
#        title: '{{ if eq .Status "firing" }}:sadparrot:{{ else }}:fastparrot:{{ end }} [{{ .Status | toUpper }}] {{ .CommonAnnotations.title }} (instances)'
#        channel: '#system_events'
#        text: >-
#          {{ range .Alerts }}
#            *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
#            *Description:* {{ .Annotations.description }}
#            *Graph:* <{{ .GeneratorURL }}|:chart_with_upwards_trend:>
#            *Runbook:* <{{ .Annotations.runbook }}|:spiral_note_pad:>
#            *Details:*
#            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
#            {{ end }}
#          {{ end }}
#        username: 'AlertManager'
#        icon_emoji: ':prometheus:'
#        api_url: '<incomming-webhook-url>'
